# Generated by Django 4.2.2 on 2024-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм id",
                max_length=50,
                null=True,
                verbose_name="Телеграм id",
            ),
        ),
    ]
